// Mock data for Ascend — UI prototype only

export const currentUser = {
  name: "Aanya Sharma",
  firstName: "Aanya",
  email: "aanya.sharma@iitd.ac.in",
  avatar: "https://images.unsplash.com/photo-1531123897727-8f129dac168b?w=200&h=200&fit=crop&crop=faces",
  verified: true,
  headline: "B.Tech Computer Science · Aspiring ML Engineer",
  university: "IIT Delhi",
  degree: "B.Tech in Computer Science",
  graduationYear: "2027",
  location: "New Delhi, India",
  bio: "Curious builder passionate about applied AI and products that create real-world impact. Open-source contributor and hackathon enthusiast.",
  completion: 86,
};

export const skills = [
  { name: "Python", level: 90, category: "Technical" },
  { name: "Machine Learning", level: 82, category: "Technical" },
  { name: "React", level: 78, category: "Technical" },
  { name: "Data Analysis", level: 85, category: "Technical" },
  { name: "UI/UX Design", level: 70, category: "Design" },
  { name: "Figma", level: 75, category: "Design" },
  { name: "Public Speaking", level: 80, category: "Soft" },
  { name: "Leadership", level: 72, category: "Soft" },
];

export const projects = [
  {
    title: "EduMate — AI Study Companion",
    description: "An LLM-powered study assistant that generates personalized revision plans and quizzes from lecture notes. Built with React, FastAPI, and a fine-tuned transformer model.",
    tags: ["AI", "React", "FastAPI"],
    link: "#",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=500&fit=crop",
  },
  {
    title: "GreenGrid — Carbon Footprint Tracker",
    description: "A sustainability dashboard that visualizes household carbon emissions and recommends reductions. Featured at the Smart India Hackathon 2025.",
    tags: ["Sustainability", "Data Viz", "Python"],
    link: "#",
    image: "https://images.unsplash.com/photo-1473341304178-82c96614d32d?w=800&h=500&fit=crop",
  },
  {
    title: "Pulse — Mental Wellness App",
    description: "A minimalist journaling app with sentiment analysis that nudges users toward healthier habits. 4.8★ on Product Hunt.",
    tags: ["Mobile", "ML", "UX"],
    link: "#",
    image: "https://images.unsplash.com/photo-1499728607263-13726abf2d44?w=800&h=500&fit=crop",
  },
];

export const certifications = [
  { name: "Google TensorFlow Developer Certificate", issuer: "Google", year: "2025", logo: "🧠" },
  { name: "Deep Learning Specialization", issuer: "DeepLearning.AI", year: "2024", logo: "🎓" },
  { name: "Meta Front-End Developer", issuer: "Meta", year: "2024", logo: "⚛️" },
];

export const achievements = [
  { title: "Smart India Hackathon — Winner", detail: "1st place out of 2,400 teams · ₹1L prize", year: "2025" },
  { title: "Google Women Techmakers Scholar", detail: "Awarded for academic excellence & community impact", year: "2025" },
  { title: "Dean's List — Top 5% of cohort", detail: "IIT Delhi, Semester 4", year: "2024" },
];

export const interests = ["Artificial Intelligence", "Sustainability", "EdTech", "Open Source", "Product Design", "Robotics"];

export const opportunities = [
  {
    id: "opp-1",
    title: "Software Engineering Intern, AI/ML",
    organization: "Google",
    type: "Internship",
    typeColor: "indigo",
    logo: "https://logo.clearbit.com/google.com",
    location: "Bengaluru, India · Hybrid",
    deadline: "2026-09-28",
    duration: "12 weeks",
    stipend: "₹80,000 / month",
    fitScore: 94,
    postedDate: "2 days ago",
    matchedSkills: ["Python", "Machine Learning", "React"],
    matchReasons: [
      "Your ML specialization and TensorFlow certification align directly with the team's applied AI work.",
      "Your EduMate project demonstrates hands-on LLM experience — a core part of this role.",
      "Strong Python proficiency (90%) exceeds the technical bar for this internship.",
    ],
    summary: "Join the Gemini Applied AI team to build and ship production-grade ML systems that power Google products used by billions.",
    eligibility: ["Currently pursuing a B.Tech/B.E.", "Graduating in 2027 or later", "Strong fundamentals in data structures & ML"],
    tags: ["AI/ML", "Backend", "Paid"],
  },
  {
    id: "opp-2",
    title: "Smart India Hackathon — Grand Finale",
    organization: "Government of India",
    type: "Hackathon",
    typeColor: "amber",
    logo: null,
    emoji: "🏆",
    location: "New Delhi, India · Onsite",
    deadline: "2026-09-15",
    duration: "36 hours",
    stipend: "₹1,00,000 prize pool",
    fitScore: 91,
    postedDate: "5 days ago",
    matchedSkills: ["Python", "UI/UX Design", "Leadership"],
    matchReasons: [
      "You're a past winner — your experience gives you a proven edge.",
      "Your sustainability project (GreenGrid) matches this year's theme perfectly.",
      "Strong team leadership skills identified from your achievements.",
    ],
    summary: "India's largest national hackathon. Build innovative solutions to real-world problem statements from government ministries in 36 hours.",
    eligibility: ["Current student of an AICTE-recognized institute", "Team of 6 members", "Open to all disciplines"],
    tags: ["Innovation", "Sustainability", "Prize"],
  },
  {
    id: "opp-3",
    title: "Google Women Techmakers Scholarship",
    organization: "Google",
    type: "Scholarship",
    typeColor: "rose",
    logo: "https://logo.clearbit.com/google.com",
    location: "India · Remote",
    deadline: "2026-10-05",
    duration: "One-time",
    stipend: "₹1,00,000",
    fitScore: 88,
    postedDate: "1 week ago",
    matchedSkills: ["Machine Learning", "Leadership", "Public Speaking"],
    matchReasons: [
      "You're a past recipient — strong narrative continuity for renewal.",
      "Community impact through mentorship aligns with scholarship values.",
      "Academic excellence (Dean's List) strengthens your application.",
    ],
    summary: "Supporting women in computer science and tech leadership. Includes financial support, mentorship, and access to the WTMs community.",
    eligibility: ["Identify as a woman in tech", "Currently enrolled full-time", "Strong academic & community record"],
    tags: ["Funding", "Mentorship", "Women in Tech"],
  },
  {
    id: "opp-4",
    title: "Research Intern — NLP & Reasoning",
    organization: "Microsoft Research",
    type: "Internship",
    typeColor: "indigo",
    logo: "https://logo.clearbit.com/microsoft.com",
    location: "Bengaluru, India · Onsite",
    deadline: "2026-10-12",
    duration: "16 weeks",
    stipend: "₹70,000 / month",
    fitScore: 85,
    postedDate: "3 days ago",
    matchedSkills: ["Machine Learning", "Python", "Data Analysis"],
    matchReasons: [
      "Your ML coursework and projects show research aptitude.",
      "Python proficiency matches the lab's primary stack.",
      "Interest in AI aligns with the lab's NLP focus area.",
    ],
    summary: "Work alongside MSR researchers on pushing the boundaries of language model reasoning. Co-author publications at top-tier venues.",
    eligibility: ["B.Tech/M.Tech in CS or related", "GPA 8.0+", "Prior research or publication preferred"],
    tags: ["Research", "NLP", "Publications"],
  },
  {
    id: "opp-5",
    title: "ACM ICPC Regional Contest",
    organization: "ACM",
    type: "Competition",
    typeColor: "violet",
    logo: null,
    emoji: "💻",
    location: "Asia Region · Online + Onsite",
    deadline: "2026-09-20",
    duration: "5 hours",
    stipend: "Prestige + Global finals",
    fitScore: 79,
    postedDate: "1 week ago",
    matchedSkills: ["Python", "Data Analysis"],
    matchReasons: [
      "Strong algorithmic foundation from your CS coursework.",
      "Python gives you a fast prototyping edge in contests.",
      "Recommended to sharpen competitive programming skills first.",
    ],
    summary: "The world's most prestigious competitive programming contest. Solve complex algorithmic problems under time pressure.",
    eligibility: ["Team of 3 students", "Same institution", "Enrolled in a degree program"],
    tags: ["Algorithms", "Competitive", "Global"],
  },
  {
    id: "opp-6",
    title: "Open Source Contributor — Mozilla Firefox",
    organization: "Mozilla Foundation",
    type: "Project",
    typeColor: "emerald",
    logo: "https://logo.clearbit.com/mozilla.org",
    location: "Remote",
    deadline: "2026-10-20",
    duration: "Ongoing",
    stipend: "Mentorship + Swag",
    fitScore: 76,
    postedDate: "4 days ago",
    matchedSkills: ["React", "UI/UX Design"],
    matchReasons: [
      "Front-end skills (React, Figma) match Firefox UI contribution areas.",
      "Your open-source interest signals cultural fit.",
      "Good entry point to build a public contribution portfolio.",
    ],
    summary: "Contribute to the world's most impactful open-source browser. Get mentored by Mozilla engineers and ship code to millions.",
    eligibility: ["Basic Git/GitHub familiarity", "Comfortable with JS/React", "Self-driven"],
    tags: ["Open Source", "Frontend", "Mentorship"],
  },
];

export const upcomingDeadlines = [
  { id: "opp-2", title: "Smart India Hackathon — Grand Finale", deadline: "2026-09-15", daysLeft: 8, type: "Hackathon" },
  { id: "opp-5", title: "ACM ICPC Regional Contest", deadline: "2026-09-20", daysLeft: 13, type: "Competition" },
  { id: "opp-1", title: "Software Engineering Intern, AI/ML", deadline: "2026-09-28", daysLeft: 21, type: "Internship" },
];

export const goalRoadmap = {
  goal: {
    title: "ML Engineer @ Google",
    organization: "Google",
    target: "Graduation 2027",
    emoji: "🎯",
    description: "Land a full-time Machine Learning Engineer role at Google after graduation.",
  },
  progress: 62,
  pitstops: [
    {
      id: 1,
      title: "Build Core Foundations",
      description: "Master Python, data structures & algorithms.",
      icon: "Code2",
      status: "done",
      tasks: [
        { label: "Complete advanced Python course", done: true },
        { label: "Solve 150 DSA problems", done: true },
        { label: "Build 2 foundational projects", done: true },
      ],
      date: "Completed · Aug 2025",
    },
    {
      id: 2,
      title: "Earn ML Credentials",
      description: "Get certified and demonstrate ML expertise.",
      icon: "Award",
      status: "done",
      tasks: [
        { label: "TensorFlow Developer Certificate", done: true },
        { label: "Deep Learning Specialization", done: true },
        { label: "Publish 1 ML blog post", done: true },
      ],
      date: "Completed · Jan 2026",
    },
    {
      id: 3,
      title: "Ship a Flagship AI Project",
      description: "Build and launch EduMate — your LLM study companion.",
      icon: "Rocket",
      status: "active",
      tasks: [
        { label: "MVP with core LLM features", done: true },
        { label: "Deploy to production", done: false },
        { label: "Reach 1,000 users", done: false },
      ],
      date: "In progress · 67% done",
    },
    {
      id: 4,
      title: "Land the Google SWE Internship",
      description: "Apply, interview, and secure the AI/ML internship.",
      icon: "Briefcase",
      status: "upcoming",
      tasks: [
        { label: "Polish resume & portfolio", done: false },
        { label: "Crack 3 mock interviews", done: false },
        { label: "Apply by Sep 28 deadline", done: false },
      ],
      date: "Deadline · Sep 28, 2026",
    },
    {
      id: 5,
      title: "Convert to Full-time Offer",
      description: "Excel during the internship and earn a return offer.",
      icon: "Trophy",
      status: "locked",
      tasks: [
        { label: "Complete internship project", done: false },
        { label: "Get strong host feedback", done: false },
        { label: "Receive return offer", done: false },
      ],
      date: "Target · 2027",
    },
  ],
};

export const feedStats = {
  totalMatches: 42,
  newThisWeek: 8,
  avgFitScore: 84,
  saved: 5,
};